import { useEffect } from 'react';
import type { Locale } from './i18n';

const content = {
  nb: {
    privacy: { title: 'Personvernerklæring', intro: 'Denne erklæringen forklarer hvordan Yasaflow behandler personopplysninger når du besøker nettsiden, oppretter konto eller bruker plattformen.', sections: [
      ['Behandlingsansvarlig', 'Yasaflow er behandlingsansvarlig for opplysninger knyttet til nettsiden og egen kundeadministrasjon. Organisasjoner som bruker plattformen er normalt behandlingsansvarlige for opplysninger de legger inn om egne medlemmer, ansatte og kontakter.'],
      ['Opplysninger vi behandler', 'Vi kan behandle navn, e-postadresse, organisasjonsopplysninger, innloggings- og sikkerhetsdata, supporthenvendelser og tekniske driftslogger. Betalingsopplysninger behandles av valgt betalingsleverandør når betaling aktiveres.'],
      ['Formål og rettslig grunnlag', 'Opplysningene brukes for å opprette og administrere kontoer, levere tjenesten, ivareta sikkerhet, gi support og oppfylle lovpålagte krav. Behandlingen bygger på avtale, berettiget interesse, samtykke der det kreves, og rettslige forpliktelser.'],
      ['Lagring og sletting', 'Opplysninger lagres så lenge de er nødvendige for kundeforholdet, sikkerhet, dokumentasjon og lovkrav. Konto- og organisasjonsdata slettes eller anonymiseres etter avsluttet kundeforhold i tråd med avtale og gjeldende regler.'],
      ['Databehandlere og overføringer', 'Vi bruker leverandører for hosting, database, e-post og teknisk drift. Det inngås nødvendige databehandleravtaler. Overføringer utenfor EØS skal sikres med gyldig overføringsgrunnlag.'],
      ['Dine rettigheter', 'Du kan be om innsyn, retting, sletting, begrensning, dataportabilitet eller protestere mot behandling. Du kan også klage til Datatilsynet.'],
      ['Kontakt', 'Spørsmål om personvern kan sendes til hello@yasaflow.com.'] ] },
    terms: { title: 'Vilkår for bruk', intro: 'Disse vilkårene gjelder bruk av Yasaflows nettside, prøveperiode og plattformtjenester.', sections: [
      ['Konto og tilgang', 'Du må oppgi korrekte opplysninger, beskytte innloggingsinformasjonen og varsle oss ved mistanke om misbruk. Tilgang kan begrenses ved sikkerhetsbrudd, ulovlig bruk eller vesentlig mislighold.'],
      ['Prøveperiode og avtale', 'Opprettelse via nettsiden kan gi en tidsbegrenset prøveperiode. Pris, moduler, betalingsvilkår og endelig aktivering bekreftes før en bindende betalt avtale starter.'],
      ['Tillatt bruk', 'Tjenesten skal brukes lovlig og i samsvar med personvernregler. Det er ikke tillatt å forsøke å omgå sikkerhet, forstyrre driften, spre skadelig kode eller bruke tjenesten til ulovlig innhold.'],
      ['Kundedata', 'Kunden beholder rettighetene til egne data og er ansvarlig for at data kan behandles lovlig. Yasaflow behandler kundedata for å levere, sikre og støtte tjenesten.'],
      ['Tilgjengelighet og endringer', 'Vi arbeider for stabil drift, men garanterer ikke uavbrutt tilgjengelighet. Vedlikehold, sikkerhetstiltak og nødvendige produktendringer kan gjennomføres.'],
      ['Ansvar', 'Yasaflow er ikke ansvarlig for indirekte tap, følgeskader eller tap som skyldes kundens feil bruk, tredjepartstjenester eller forhold utenfor vår rimelige kontroll, så langt loven tillater.'],
      ['Oppsigelse', 'Avtalen kan sies opp i henhold til valgt abonnementsavtale. Ved avslutning håndteres eksport og sletting av data etter avtalen og gjeldende lov.'],
      ['Kontakt og lovvalg', 'Spørsmål sendes til hello@yasaflow.com. Norsk rett gjelder, med mindre ufravikelige regler bestemmer noe annet.'] ] },
    cookies: { title: 'Informasjon om informasjonskapsler', intro: 'Yasaflow bruker bare informasjonskapsler og lokal lagring som er nødvendige for sikkerhet, språkvalg, innlogging og funksjonalitet, med mindre du senere samtykker til analyse eller markedsføring.', sections: [
      ['Nødvendig lagring', 'Nødvendige data kan brukes for sesjon, autentisering, språkvalg og for å fullføre registreringsprosessen. Disse er nødvendige for at tjenesten skal fungere.'],
      ['Analyse og markedsføring', 'Analyse- eller markedsføringsverktøy skal ikke aktiveres før et gyldig samtykke er innhentet der dette kreves.'],
      ['Administrasjon', 'Du kan slette informasjonskapsler og nettstedsdata i nettleseren. Dette kan logge deg ut eller avbryte en pågående registrering.'] ] }
  },
  en: {
    privacy: { title: 'Privacy notice', intro: 'This notice explains how Yasaflow processes personal data when you visit the website, create an account or use the platform.', sections: [['Controller and roles','Yasaflow controls website and customer-administration data. Customer organizations normally control the member and contact data they upload.'],['Data and purposes','We may process identity, contact, organization, login, security, support and technical log data to provide, secure and support the service and meet legal obligations.'],['Retention and suppliers','Data is retained only as necessary. We use vetted hosting, database and email suppliers under appropriate agreements and safeguards.'],['Your rights','You may request access, correction, deletion, restriction, portability or object to processing. Contact hello@yasaflow.com.']] },
    terms: { title: 'Terms of use', intro: 'These terms apply to Yasaflow’s website, trial and platform services.', sections: [['Accounts','Provide accurate details and protect your credentials. Access may be restricted for misuse or security reasons.'],['Trial and subscription','Website registration may start a limited trial. Pricing, modules and payment terms are confirmed before a binding paid subscription begins.'],['Acceptable use','Do not break laws, bypass security, disrupt the service or upload malicious or unlawful content.'],['Customer data and availability','Customers retain rights to their data. We aim for reliable availability but may perform maintenance and security changes.'],['Liability and termination','Liability is limited to the extent permitted by law. Termination, export and deletion follow the subscription agreement and applicable law.'],['Contact','Contact hello@yasaflow.com. Norwegian law applies unless mandatory rules state otherwise.']] },
    cookies: { title: 'Cookie information', intro: 'Yasaflow uses necessary cookies and local storage for security, language, authentication and core functionality.', sections: [['Necessary storage','Session, authentication, language and onboarding state may be stored to make the service work.'],['Optional tools','Analytics or marketing tools will require consent where applicable.'],['Controls','You can clear website data in your browser, but this may sign you out or interrupt onboarding.']] }
  },
  tr: {
    privacy: { title: 'Gizlilik bildirimi', intro: 'Bu bildirim, Yasaflow’un web sitesi, hesap oluşturma ve platform kullanımı sırasında kişisel verileri nasıl işlediğini açıklar.', sections: [['Roller ve veriler','Yasaflow web sitesi ve müşteri yönetimi verilerinden sorumludur. Kuruluşlar kendi yükledikleri üye ve iletişim verilerinden genellikle kendileri sorumludur.'],['Amaçlar','Kimlik, iletişim, kuruluş, giriş, güvenlik, destek ve teknik kayıt verileri hizmeti sunmak ve korumak için işlenebilir.'],['Saklama ve haklar','Veriler yalnızca gerekli olduğu sürece saklanır. Erişim, düzeltme, silme ve diğer haklarınız için hello@yasaflow.com adresine yazabilirsiniz.']] },
    terms: { title: 'Kullanım koşulları', intro: 'Bu koşullar Yasaflow web sitesi, deneme süresi ve platform hizmetleri için geçerlidir.', sections: [['Hesap','Doğru bilgi verin ve giriş bilgilerinizi koruyun. Kötüye kullanım veya güvenlik riski durumunda erişim sınırlandırılabilir.'],['Deneme ve abonelik','Kayıt sınırlı bir deneme başlatabilir. Ücretli sözleşmeden önce fiyat, modüller ve ödeme koşulları onaylanır.'],['Kullanım ve veriler','Hizmeti yasal kullanın; güvenliği aşmayın veya zararlı içerik yüklemeyin. Müşteri kendi verilerinin haklarını korur.'],['İletişim','Sorular için hello@yasaflow.com adresine yazın. Zorunlu kurallar aksini gerektirmedikçe Norveç hukuku uygulanır.']] },
    cookies: { title: 'Çerez bilgisi', intro: 'Yasaflow güvenlik, dil, giriş ve temel işlevler için gerekli çerezleri ve yerel depolamayı kullanır.', sections: [['Gerekli depolama','Oturum, kimlik doğrulama, dil ve kayıt süreci bilgileri hizmetin çalışması için saklanabilir.'],['İsteğe bağlı araçlar','Analiz veya pazarlama araçları gerektiğinde onay alınmadan etkinleştirilmez.'],['Kontrol','Tarayıcıdan site verilerini silebilirsiniz; bu işlem oturumu veya kayıt sürecini sonlandırabilir.']] }
  }
} as const;

export default function LegalPage({ type, locale }: { type: 'privacy' | 'terms' | 'cookies'; locale: Locale }) {
  const page = content[locale][type];
  useEffect(() => { document.title = `${page.title} — Yasaflow`; }, [page.title]);
  return <main className="min-h-screen bg-slate-50 px-5 py-14 text-slate-900"><article className="mx-auto max-w-3xl rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm sm:p-12"><a href="/" className="font-semibold text-[#2185DC]">← Yasaflow</a><p className="mt-8 text-sm font-semibold uppercase tracking-wider text-[#2185DC]">Sist oppdatert 14. juli 2026</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{page.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{page.intro}</p><div className="mt-10 space-y-9">{page.sections.map(([heading, body]) => <section key={heading}><h2 className="text-xl font-semibold">{heading}</h2><p className="mt-3 leading-7 text-slate-600">{body}</p></section>)}</div><div className="mt-12 border-t border-slate-200 pt-6 text-sm text-slate-500"><a className="mr-5 hover:text-[#2185DC]" href="/privacy">Privacy</a><a className="mr-5 hover:text-[#2185DC]" href="/terms">Terms</a><a className="hover:text-[#2185DC]" href="/cookies">Cookies</a></div></article></main>;
}
