import { useEffect } from 'react';
import type { Locale } from './i18n';

type LegalType = 'privacy' | 'terms' | 'refund' | 'cookies';
type Page = { title: string; intro: string; sections: readonly (readonly [string, string])[] };

const content: Record<Locale, Record<LegalType, Page>> = {
  nb: {
    privacy: { title: 'Personvernerklæring', intro: 'Denne erklæringen forklarer hvordan Yasaflow behandler personopplysninger når du besøker nettsiden, oppretter konto eller bruker plattformen.', sections: [
      ['Behandlingsansvarlig', 'Yasaflow er behandlingsansvarlig for nettside- og kundeadministrasjonsdata. Organisasjoner er normalt behandlingsansvarlige for opplysninger de registrerer om egne medlemmer og kontakter.'],
      ['Opplysninger og formål', 'Vi kan behandle navn, e-post, organisasjonsopplysninger, innloggings- og sikkerhetsdata, supporthenvendelser og tekniske logger for å levere og sikre tjenesten, gi support og oppfylle lovkrav.'],
      ['Betaling og leverandører', 'Betaling behandles av Paddle som betalingsleverandør og Merchant of Record. Vi bruker også leverandører for hosting, database, e-post og teknisk drift under nødvendige avtaler og sikkerhetstiltak.'],
      ['Lagring og rettigheter', 'Opplysninger lagres så lenge det er nødvendig. Du kan be om innsyn, retting, sletting, begrensning eller dataportabilitet, protestere mot behandling og klage til Datatilsynet.'],
      ['Kontakt', 'Spørsmål om personvern kan sendes til hello@yasaflow.com.'] ] },
    terms: { title: 'Vilkår for bruk', intro: 'Disse vilkårene gjelder Yasaflows nettside, 7 dagers prøveperiode og betalte abonnementstjenester.', sections: [
      ['Konto og tilgang', 'Du må oppgi korrekte opplysninger og beskytte innloggingsinformasjonen. Tilgang kan begrenses ved misbruk, sikkerhetsbrudd eller vesentlig mislighold.'],
      ['Prøveperiode og pris', 'Yasaflow tilbyr 7 dager gratis. Deretter koster grunnplattformen fra 349 kr per måned. Valgfrie tilleggsmoduler kan øke månedsprisen. Den totale abonnementsprisen vises tydelig før kjøpet bekreftes.'],
      ['Automatisk fornyelse', 'Abonnementet fornyes automatisk for hver betalingsperiode til det sies opp. Avslutt før prøveperioden utløper for å unngå belastning.'],
      ['Oppsigelse', 'Abonnementet kan sies opp gjennom abonnementsportalen eller betalingsbekreftelsen fra Paddle. Etter oppsigelse beholdes normalt tilgang ut inneværende, allerede betalte periode.'],
      ['Tillatt bruk og kundedata', 'Tjenesten skal brukes lovlig. Kunden beholder rettighetene til egne data og er ansvarlig for at data kan behandles lovlig.'],
      ['Tilgjengelighet og ansvar', 'Vi arbeider for stabil drift, men kan gjennomføre vedlikehold og sikkerhetsendringer. Ansvar begrenses så langt gjeldende lov tillater.'],
      ['Refusjon og lovvalg', 'Refusjoner håndteres etter refusjonspolicyen, gjeldende lov og Paddles regler. Norsk rett gjelder med mindre ufravikelige regler bestemmer noe annet.'],
      ['Kontakt', 'Spørsmål kan sendes til hello@yasaflow.com.'] ] },
    refund: { title: 'Refusjons- og kanselleringspolicy', intro: 'Denne policyen forklarer gratis prøveperiode, automatisk fornyelse, oppsigelse og refusjon for Yasaflow-abonnementer.', sections: [
      ['7 dagers gratis prøveperiode', 'Du belastes ikke i prøveperioden. Dersom abonnementet ikke avsluttes før prøveperioden utløper, starter det valgte betalte abonnementet automatisk.'],
      ['Pris og tilleggsmoduler', 'Grunnplattformen koster fra 349 kr per måned. Valgfrie tilleggsmoduler legges til månedsprisen. Den totale prisen, inkludert valgte moduler, vises før kjøpet bekreftes.'],
      ['Oppsigelse', 'Du kan si opp når som helst gjennom abonnementsportalen eller lenken i e-posten fra Paddle. Oppsigelsen stopper fremtidige fornyelser.'],
      ['Refusjoner', 'Betalinger for påbegynte abonnementsperioder refunderes normalt ikke, med mindre gjeldende lov gir rett til refusjon, belastningen er feil eller duplisert, tjenesten har en vesentlig uløst feil, eller Paddle godkjenner refusjonen. Manglende bruk gir normalt ikke rett til refusjon.'],
      ['Forbrukerrettigheter', 'Lovbestemt angrerett og andre ufravikelige forbrukerrettigheter påvirkes ikke av denne policyen. Bedriftskjøp omfattes normalt ikke av forbrukernes angrerett.'],
      ['Slik ber du om refusjon', 'Bruk lenken i betalingsbekreftelsen fra Paddle, Paddles kjøperportal eller kontakt hello@yasaflow.com. Oppgi e-postadresse, organisasjonsnavn, betalingsdato og årsaken til forespørselen.'] ] },
    cookies: { title: 'Informasjon om informasjonskapsler', intro: 'Yasaflow bruker nødvendige informasjonskapsler og lokal lagring for sikkerhet, språk, innlogging og funksjonalitet.', sections: [['Nødvendig lagring', 'Sesjon, autentisering, språkvalg og registreringsstatus kan lagres for at tjenesten skal fungere.'],['Valgfrie verktøy', 'Analyse eller markedsføring aktiveres ikke uten samtykke der dette kreves.'],['Kontroll', 'Du kan slette nettstedsdata i nettleseren, men dette kan logge deg ut eller avbryte registreringen.']] }
  },
  en: {
    privacy: { title: 'Privacy policy', intro: 'This policy explains how Yasaflow processes personal data when you visit the website, create an account or use the platform.', sections: [['Controller and data','Yasaflow controls website and customer-administration data. Customer organizations normally control member and contact data they upload.'],['Purposes and suppliers','We process account, organization, security, support and technical data to provide and protect the service. Paddle processes payments as Merchant of Record.'],['Retention and rights','Data is kept only as necessary. You may request access, correction, deletion, restriction or portability and object to processing.'],['Contact','Contact hello@yasaflow.com.']] },
    terms: { title: 'Terms and conditions', intro: 'These terms apply to the Yasaflow website, 7-day free trial and paid subscriptions.', sections: [['Trial and pricing','The trial is free for 7 days. After that, the core platform starts from NOK 349 per month. Optional add-on modules can increase the monthly price. The total subscription price is shown before purchase.'],['Automatic renewal','The subscription renews automatically until cancelled. Cancel before the trial ends to avoid being charged.'],['Cancellation','You may cancel through the subscription portal or the link in Paddle emails. Cancellation stops future renewals and access normally continues through the paid period.'],['Use, data and availability','Use the service lawfully and protect your account. Customers retain rights to their data. Maintenance and security changes may occur.'],['Refunds and law','Refunds follow the refund policy, applicable law and Paddle rules. Norwegian law applies unless mandatory law states otherwise.'],['Contact','Contact hello@yasaflow.com.']] },
    refund: { title: 'Refund and cancellation policy', intro: 'This policy explains the free trial, automatic renewal, cancellation and refunds for Yasaflow subscriptions.', sections: [['7-day free trial','You are not charged during the trial. Unless cancelled before it ends, the selected paid subscription starts automatically.'],['Price and add-ons','The core platform starts from NOK 349 per month. Optional add-on modules are added to the monthly price. The complete total is displayed before purchase.'],['Cancellation','Cancel at any time through the subscription portal or Paddle email link. Cancellation stops future renewals.'],['Refunds','Payments for started billing periods are normally non-refundable unless required by law, charged incorrectly or twice, affected by a material unresolved service fault, or approved by Paddle. Non-use does not normally qualify for a refund.'],['Consumer rights','Mandatory cancellation, withdrawal and consumer rights are not limited by this policy. Business purchases do not normally receive consumer withdrawal rights.'],['Requesting a refund','Use the link in your Paddle receipt, Paddle buyer portal, or email hello@yasaflow.com with your account email, organization name, payment date and reason.']] },
    cookies: { title: 'Cookie information', intro: 'Yasaflow uses necessary cookies and local storage for security, language, authentication and core functionality.', sections: [['Necessary storage','Session, authentication, language and onboarding state may be stored.'],['Optional tools','Analytics or marketing tools require consent where applicable.'],['Controls','Clearing site data may sign you out or interrupt onboarding.']] }
  },
  tr: {
    privacy: { title: 'Gizlilik politikası', intro: 'Bu politika Yasaflow’un web sitesi, hesap ve platform kullanımındaki kişisel verileri nasıl işlediğini açıklar.', sections: [['Veriler ve roller','Yasaflow web sitesi ve müşteri yönetimi verilerini işler. Kuruluşlar yükledikleri üye verilerinden genellikle kendileri sorumludur.'],['Amaç ve sağlayıcılar','Hizmeti sunmak ve korumak için hesap, güvenlik, destek ve teknik veriler işlenebilir. Ödemeler Paddle tarafından işlenir.'],['Haklar ve iletişim','Erişim, düzeltme, silme ve diğer haklarınız için hello@yasaflow.com adresine yazabilirsiniz.']] },
    terms: { title: 'Kullanım koşulları', intro: 'Bu koşullar Yasaflow web sitesi, 7 günlük ücretsiz deneme ve ücretli abonelikler için geçerlidir.', sections: [['Deneme ve fiyat','İlk 7 gün ücretsizdir. Sonrasında temel platform aylık 349 NOK’dan başlar. Seçilen ek modüller aylık fiyatı artırabilir ve toplam fiyat satın almadan önce gösterilir.'],['Otomatik yenileme','Abonelik iptal edilene kadar otomatik yenilenir. Ücret alınmaması için deneme bitmeden iptal edin.'],['İptal ve iade','İptal Paddle bağlantısı veya abonelik portalından yapılabilir. İadeler iade politikası, geçerli hukuk ve Paddle kurallarına göre değerlendirilir.'],['İletişim','hello@yasaflow.com adresine yazabilirsiniz.']] },
    refund: { title: 'İade ve iptal politikası', intro: 'Bu politika Yasaflow aboneliklerinin ücretsiz deneme, yenileme, iptal ve iade şartlarını açıklar.', sections: [['7 günlük deneme','Deneme süresinde ücret alınmaz. Süre bitmeden iptal edilmezse seçilen ücretli abonelik otomatik başlar.'],['Fiyat ve modüller','Temel platform aylık 349 NOK’dan başlar. Ek modüller toplam fiyata eklenir ve toplam tutar satın almadan önce gösterilir.'],['İptal','Abonelik portalı veya Paddle e-postasındaki bağlantı üzerinden iptal ederek gelecekteki yenilemeleri durdurabilirsiniz.'],['İadeler','Başlamış ödeme dönemleri, kanunen gerekli olmadıkça, hatalı veya mükerrer ödeme olmadıkça ya da Paddle onaylamadıkça normalde iade edilmez.'],['Talep','Paddle makbuz bağlantısını, alıcı portalını veya hello@yasaflow.com adresini kullanın.']] },
    cookies: { title: 'Çerez bilgisi', intro: 'Yasaflow güvenlik, dil, giriş ve temel işlevler için gerekli çerezleri kullanır.', sections: [['Gerekli depolama','Oturum, kimlik doğrulama, dil ve kayıt bilgileri saklanabilir.'],['İsteğe bağlı araçlar','Analiz veya pazarlama için gerektiğinde onay alınır.'],['Kontrol','Site verilerini silmek oturumu kapatabilir.']] }
  }
};

export default function LegalPage({ type, locale }: { type: LegalType; locale: Locale }) {
  const page = content[locale][type];
  useEffect(() => { document.title = `${page.title} — Yasaflow`; }, [page.title]);
  return <main className="min-h-screen bg-slate-50 px-5 py-14 text-slate-900"><article className="mx-auto max-w-3xl rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm sm:p-12"><a href="/" className="font-semibold text-[#2185DC]">← Yasaflow</a><p className="mt-8 text-sm font-semibold uppercase tracking-wider text-[#2185DC]">Sist oppdatert 17. juli 2026</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{page.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{page.intro}</p><div className="mt-10 space-y-9">{page.sections.map(([heading, body]) => <section key={heading}><h2 className="text-xl font-semibold">{heading}</h2><p className="mt-3 leading-7 text-slate-600">{body}</p></section>)}</div><div className="mt-12 flex flex-wrap gap-5 border-t border-slate-200 pt-6 text-sm text-slate-500"><a className="hover:text-[#2185DC]" href="/privacy">Privacy</a><a className="hover:text-[#2185DC]" href="/terms">Terms</a><a className="hover:text-[#2185DC]" href="/refund">Refunds</a><a className="hover:text-[#2185DC]" href="/cookies">Cookies</a></div></article></main>;
}
