import { useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, Loader2, X } from 'lucide-react';
import { supabase } from './lib/supabase';

type Organization = {
  id:string; name:string; slug:string|null; organization_type:string|null; country:string|null; language:string|null; logo_url:string|null;
};
type Settings = { description:string; timezone:string; email:string; phone:string; address:string; logo_url:string; favicon_url:string };

type Props = { organization:Organization; onClose:()=>void; onSaved:()=>Promise<void> };
const types=['Moské','Kirke','Borettslag / sameie','Idrettslag','Forening','Skole','Kommunal organisasjon','Annet'];
const languages=['Norsk','English','Türkçe','العربية','اردو'];
const zones=['Europe/Oslo','Europe/Stockholm','Europe/Copenhagen','Europe/London','Europe/Berlin','Europe/Istanbul','Asia/Dubai','Asia/Qatar'];
const normalizeSlug=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48);
const input='mt-1 w-full rounded-xl border border-slate-200 bg-white p-3 outline-none focus:border-blue-500';

export default function OrganizationSettingsModal({organization,onClose,onSaved}:Props){
  const [form,setForm]=useState({name:organization.name,slug:organization.slug||'',organizationType:organization.organization_type||'Forening',country:organization.country||'Norge',language:organization.language||'Norsk',description:'',timezone:'Europe/Oslo',email:'',phone:'',address:'',logoUrl:organization.logo_url||'',faviconUrl:''});
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [slugAvailable,setSlugAvailable]=useState<boolean|null>(null);

  useEffect(()=>{const load=async()=>{if(!supabase)return;const {data}=await supabase.from('organization_settings').select('description,timezone,email,phone,address,logo_url,favicon_url').eq('organization_id',organization.id).maybeSingle();const value=(data||{}) as Partial<Settings>;setForm(current=>({...current,description:value.description||'',timezone:value.timezone||'Europe/Oslo',email:value.email||'',phone:value.phone||'',address:value.address||'',logoUrl:value.logo_url||current.logoUrl,faviconUrl:value.favicon_url||''}));setLoading(false);};void load();},[organization.id]);
  useEffect(()=>{if(!supabase||form.slug.length<3){setSlugAvailable(null);return;}const timer=setTimeout(async()=>{const {data}=await supabase!.rpc('is_organization_slug_available',{p_slug:form.slug,p_exclude_organization_id:organization.id});setSlugAvailable(Boolean(data));},300);return()=>clearTimeout(timer);},[form.slug,organization.id]);

  const submit=async(event:FormEvent)=>{event.preventDefault();if(!supabase)return;if(slugAvailable===false)return setError('Appadressen er allerede opptatt.');setBusy(true);setError('');setSaved(false);const {error}=await supabase.rpc('update_customer_portal_organization',{p_organization_id:organization.id,p_name:form.name.trim(),p_organization_type:form.organizationType,p_country:form.country.trim(),p_language:form.language,p_slug:normalizeSlug(form.slug),p_description:form.description.trim(),p_timezone:form.timezone,p_email:form.email.trim(),p_phone:form.phone.trim(),p_address:form.address.trim(),p_logo_url:form.logoUrl.trim(),p_favicon_url:form.faviconUrl.trim()});if(error){setError(error.message);setBusy(false);return;}await onSaved();setSaved(true);setBusy(false);};

  return <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-slate-950/55 p-4 py-8"><div className="w-full max-w-3xl rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-6 py-5"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-600">Kundeportal</p><h2 className="text-2xl font-semibold">Organisasjonsinnstillinger</h2></div><button onClick={onClose} className="rounded-xl border p-2" aria-label="Lukk"><X size={20}/></button></div>{loading?<div className="flex justify-center p-16"><Loader2 className="animate-spin text-blue-600"/></div>:<form onSubmit={submit} className="space-y-6 p-6">
    <section><h3 className="text-lg font-semibold">Grunnleggende informasjon</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Organisasjonsnavn<input required className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="text-sm font-medium">Organisasjonstype<select className={input} value={form.organizationType} onChange={e=>setForm({...form,organizationType:e.target.value})}>{types.map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-medium">Land<input className={input} value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label><label className="text-sm font-medium">Standardspråk<select className={input} value={form.language} onChange={e=>setForm({...form,language:e.target.value})}>{languages.map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-medium sm:col-span-2">Beskrivelse<textarea rows={4} className={input} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div></section>
    <section><h3 className="text-lg font-semibold">Appadresse og tidssone</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Appadresse<div className="mt-1 flex overflow-hidden rounded-xl border border-slate-200"><input required className="min-w-0 flex-1 p-3 outline-none" value={form.slug} onChange={e=>setForm({...form,slug:normalizeSlug(e.target.value)})}/><span className="flex items-center bg-slate-50 px-3 text-sm text-slate-500">.yasaflow.com</span></div><span className={`mt-1 block text-xs ${slugAvailable===false?'text-red-600':slugAvailable===true?'text-green-600':'text-slate-400'}`}>{slugAvailable===false?'Adressen er opptatt':slugAvailable===true?'Adressen er ledig':'Kontrollerer adressen'}</span></label><label className="text-sm font-medium">Tidssone<select className={input} value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}>{zones.map(v=><option key={v}>{v}</option>)}</select></label></div></section>
    <section><h3 className="text-lg font-semibold">Kontaktinformasjon</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">E-post<input type="email" className={input} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="text-sm font-medium">Telefon<input className={input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="text-sm font-medium sm:col-span-2">Adresse<input className={input} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div></section>
    <section><h3 className="text-lg font-semibold">Profil og ikon</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Logo-URL<input type="url" className={input} value={form.logoUrl} onChange={e=>setForm({...form,logoUrl:e.target.value})}/></label><label className="text-sm font-medium">Favicon-/appikon-URL<input type="url" className={input} value={form.faviconUrl} onChange={e=>setForm({...form,faviconUrl:e.target.value})}/></label></div><p className="mt-2 text-xs text-slate-500">Direkte bildeopplasting kobles på i neste steg. Foreløpig kan en bildeadresse brukes.</p></section>
    {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{saved&&<p className="flex items-center gap-2 rounded-xl bg-green-50 p-3 text-sm text-green-700"><CheckCircle2 size={17}/>Endringene er lagret.</p>}
    <div className="flex flex-col-reverse gap-3 border-t pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-xl border px-5 py-3 font-semibold">Avbryt</button><button disabled={busy||slugAvailable===false} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-60">{busy&&<Loader2 size={17} className="animate-spin"/>}{busy?'Lagrer...':'Lagre endringer'}</button></div>
  </form>}</div></div>;
}
